import type {
  Judgment,
  PendingQuestion,
  Profile,
  Settings,
  Signals,
  Summary,
  Transaction,
  SpendingPlanState,
} from "./types";

export const demoProfile: Profile = {
  monthly_income_krw: 3_500_000,
  liquid_assets_krw: 10_000_000,
  fixed_expenses_krw: 1_400_000,
  monthly_debt_payment_krw: 300_000,
  discretionary_budget_krw: 800_000,
  goal: {
    goal_id: "goal-demo",
    name: "비상금",
    target_amount_krw: 10_000_000,
    current_amount_krw: 3_000_000,
    target_date: "2027-08-03",
  },
};

export const demoSettings: Settings = {
  roast_enabled: false,
  locale: "ko-KR",
  timezone: "Asia/Seoul",
  spending_rules: ["배달은 주 2회까지", "친구와의 만남 비용은 월 4회까지 괜찮음"],
  accounts: [
    { account_id: "cash", name: "현금", account_type: "cash", opening_balance_krw: 300_000, archived: false },
    { account_id: "bank", name: "생활비 통장", account_type: "bank", opening_balance_krw: 2_000_000, archived: false },
  ],
  category_budgets_krw: { food: 300_000, cafe: 100_000, shopping: 150_000 },
};

const demoTotalSpentKrw = 377_500;
export const demoBudgetUsage = demoTotalSpentKrw / demoProfile.discretionary_budget_krw;

export const demoTransactions: Transaction[] = [
  {
    transaction_id: "tx-cafe",
    transaction_type: "expense",
    account_id: "bank",
    destination_account_id: null,
    exclude_from_budget: false,
    amount_krw: 12_000,
    merchant: "카페 온도",
    category: "cafe",
    description: null,
    occurred_at: "2026-08-03T02:45:00Z",
    source: "manual",
    source_reference: null,
    reason: "친구와 오랜만에 만나서 이야기할 곳이 필요했어.",
    status: "judged",
    created_at: "2026-08-03T02:45:00Z",
    reflection: "well_spent",
    reflection_note: "친구와 좋은 시간을 보냈어요.",
    reflected_at: "2026-08-04T02:45:00Z",
  },
  {
    transaction_id: "tx-lunch",
    transaction_type: "expense",
    account_id: "bank",
    destination_account_id: null,
    exclude_from_budget: false,
    amount_krw: 9_000,
    merchant: "점심",
    category: "food",
    description: null,
    occurred_at: "2026-08-03T03:34:00Z",
    source: "manual",
    source_reference: null,
    reason: null,
    status: "judged",
    created_at: "2026-08-03T03:34:00Z",
    reflection: "regretted",
    reflection_note: "습관적으로 사 먹었어요.",
    reflected_at: "2026-08-04T03:34:00Z",
  },
  {
    transaction_id: "tx-transit",
    transaction_type: "expense",
    account_id: "bank",
    destination_account_id: null,
    exclude_from_budget: false,
    amount_krw: 1_500,
    merchant: "교통카드",
    category: "transport",
    description: null,
    occurred_at: "2026-08-03T00:22:00Z",
    source: "manual",
    source_reference: null,
    reason: null,
    status: "judged",
    created_at: "2026-08-03T00:22:00Z",
  },
  {
    transaction_id: "tx-grocery",
    transaction_type: "expense",
    account_id: "bank",
    destination_account_id: null,
    exclude_from_budget: false,
    amount_krw: 64_000,
    merchant: "마켓컬리",
    category: "food",
    description: "주간 장보기",
    occurred_at: "2026-08-02T09:20:00Z",
    source: "manual",
    source_reference: null,
    reason: "일주일 식재료",
    status: "judged",
    created_at: "2026-08-02T09:20:00Z",
  },
  {
    transaction_id: "tx-store",
    transaction_type: "expense",
    account_id: "bank",
    destination_account_id: null,
    exclude_from_budget: false,
    amount_krw: 18_500,
    merchant: "편의점",
    category: "shopping",
    description: null,
    occurred_at: "2026-08-01T12:10:00Z",
    source: "manual",
    source_reference: null,
    reason: null,
    status: "judged",
    created_at: "2026-08-01T12:10:00Z",
    reflection: "regretted",
    reflection_note: "습관적으로 들렀어요.",
    reflected_at: "2026-08-02T12:10:00Z",
  },
  {
    transaction_id: "tx-cafe-previous-1",
    transaction_type: "expense",
    account_id: "cash",
    destination_account_id: null,
    exclude_from_budget: false,
    amount_krw: 28_000,
    merchant: "브루클린 커피",
    category: "cafe",
    description: null,
    occurred_at: "2026-08-01T06:20:00Z",
    source: "manual",
    source_reference: null,
    reason: null,
    status: "judged",
    created_at: "2026-08-01T06:20:00Z",
  },
  {
    transaction_id: "tx-cafe-previous-2",
    transaction_type: "expense",
    account_id: "cash",
    destination_account_id: null,
    exclude_from_budget: false,
    amount_krw: 32_000,
    merchant: "카페 정원",
    category: "cafe",
    description: null,
    occurred_at: "2026-08-01T01:30:00Z",
    source: "manual",
    source_reference: null,
    reason: null,
    status: "judged",
    created_at: "2026-08-01T01:30:00Z",
  },
];

export const demoSummary: Summary = {
  month: "2026-08",
  total_spent_krw: demoTotalSpentKrw,
  total_income_krw: 3_500_000,
  net_cashflow_krw: 3_122_500,
  transfer_total_krw: 0,
  by_category_krw: {
    food: 160_000,
    shopping: 95_000,
    cafe: 72_000,
    transport: 50_500,
  },
  transaction_count: 14,
  discretionary_budget_krw: demoProfile.discretionary_budget_krw,
  budget_usage: demoBudgetUsage,
  budget_spent_krw: demoTotalSpentKrw,
  previous_month: {
    month: "2026-07",
    total_spent_krw: 412_000,
    change_krw: -34_500,
    change_rate: -0.0837,
  },
  category_budgets: {
    food: { budget_krw: 300_000, spent_krw: 160_000, remaining_krw: 140_000, usage: 0.5333, daily_allowance_krw: 5_385 },
    cafe: { budget_krw: 100_000, spent_krw: 72_000, remaining_krw: 28_000, usage: 0.72, daily_allowance_krw: 1_077 },
    shopping: { budget_krw: 150_000, spent_krw: 95_000, remaining_krw: 55_000, usage: 0.6333, daily_allowance_krw: 2_115 },
  },
  account_balances: [
    { ...demoSettings.accounts[0], balance_krw: 240_000 },
    { ...demoSettings.accounts[1], balance_krw: 4_682_500 },
  ],
  goal: demoProfile.goal,
  reflection_summary: {
    reflected_count: 3,
    well_spent_count: 1,
    unsure_count: 0,
    regretted_count: 2,
    regretted_spent_krw: 27_500,
    regret_rate: 0.6667,
    strongest_regret_category: "shopping",
    goal_delay_days: 1,
  },
  weekly_briefing: {
    period_start: "2026-08-03",
    period_end: "2026-08-09",
    total_spent_krw: 22_500,
    transaction_count: 3,
    top_category: "cafe",
    top_category_spent_krw: 12_000,
    judged_count: 3,
    justified_count: 2,
    caution_count: 1,
    overspending_count: 0,
    insufficient_context_count: 0,
    headline: "이번 주 식비에서 후회한 소비 1건이 보여요.",
    summary: "이번 주 3건에 22,500원을 썼어요.",
    improvement: "이번 주 식비 지출을 1회 줄이고, 절약한 금액을 비상금에 남겨둬요.",
    concern: {
      transaction_id: "tx-cafe",
      label: "caution",
      category: "cafe",
      merchant: "카페 온도",
      amount_krw: 12_000,
      rationale: "이번 주 카페 지출이 반복됐어요.",
    },
    evidence_state: "learned",
    regret_pattern: {
      category: "food",
      category_name: "식비",
      count: 1,
      spent_krw: 9_000,
    },
    goal_impact_days: 1,
  },
};

export const demoPlanState: SpendingPlanState = {
  plan: {
    plan_id: "plan-demo",
    period_start: "2026-08-01",
    period_end: "2026-08-31",
    confirmed_budget_krw: 800_000,
    priorities: [
      { priority_id: "priority-1", name: "친구와의 약속", rank: 1 },
      { priority_id: "priority-2", name: "건강", rank: 2 },
    ],
    allocations: [
      { allocation_id: "segment-1", label: "1주차", start_date: "2026-08-01", end_date: "2026-08-03", amount_krw: 200_000 },
      { allocation_id: "segment-2", label: "2주차", start_date: "2026-08-04", end_date: "2026-08-10", amount_krw: 200_000 },
      { allocation_id: "segment-3", label: "3주차", start_date: "2026-08-11", end_date: "2026-08-17", amount_krw: 200_000 },
      { allocation_id: "segment-4", label: "남은 기간", start_date: "2026-08-18", end_date: "2026-08-31", amount_krw: 200_000 },
    ],
    planned_expenses: [
      { planned_expense_id: "planned-gift", name: "생일 선물", amount_krw: 100_000, due_date: "2026-08-20", category: "shopping", matched_transaction_id: null, matched_at: null },
    ],
    status: "active",
    version: 1,
    confirmed_at: "2026-08-01T00:00:00Z",
    created_at: "2026-08-01T00:00:00Z",
    updated_at: "2026-08-03T03:00:00Z",
    revisions: [],
    check_ins: [],
  },
  original_plan: {
    plan_id: "plan-demo",
    period_start: "2026-08-01",
    period_end: "2026-08-31",
    confirmed_budget_krw: 800_000,
    priorities: [
      { priority_id: "priority-1", name: "친구와의 약속", rank: 1 },
      { priority_id: "priority-2", name: "건강", rank: 2 },
    ],
    allocations: [],
    planned_expenses: [],
    status: "active",
    version: 1,
    confirmed_at: "2026-08-01T00:00:00Z",
    created_at: "2026-08-01T00:00:00Z",
    updated_at: "2026-08-03T03:00:00Z",
  },
  progress: {
    period_start: "2026-08-01",
    period_end: "2026-08-31",
    confirmed_budget_krw: 800_000,
    actual_spent_krw: 377_500,
    reserved_remaining_krw: 100_000,
    total_remaining_krw: 422_500,
    flexible_remaining_krw: 322_500,
    shortfall_krw: 0,
    segments: [
      { allocation_id: "segment-1", label: "1주차", start_date: "2026-08-01", end_date: "2026-08-03", amount_krw: 200_000, actual_spent_krw: 137_500, reserved_remaining_krw: 0, total_remaining_krw: 62_500, flexible_remaining_krw: 62_500 },
    ],
    current_segment_id: "segment-1",
    latest_input_at: "2026-08-03T02:45:00Z",
  },
  next_action: "이번 구간 남은 생활비 안에서 다음 지출 한 건을 기록하세요.",
  narrative: {
    headline: "현재 구간은 계획 안에서 움직이고 있어요.",
    explanation: "입력된 거래와 아직 남은 예약을 분리해 생활비 흐름을 확인했어요.",
    segment_focuses: [{ allocation_id: "segment-1", focus: "우선순위와 예약을 먼저 확인하세요." }],
    next_action: "다음 지출 전에 현재 구간의 남은 생활비를 확인하세요.",
    assumptions: ["사용자가 직접 입력한 거래가 최신 상태라고 가정했어요."],
    confidence: "medium",
    fallback_used: true,
  },
};

export const demoSignals: Signals = {
  budget_usage_after: demoBudgetUsage,
  transaction_budget_share: 0.015,
  goal_pressure: 0.7,
  baseline_deviation: 1.4,
  recurrence_30d: demoTransactions.filter((transaction) => transaction.category === "cafe").length,
  essentiality: 0.2,
  risk_score: 0.66,
  data_confidence: 0.81,
  requires_reason: true,
  factors: ["budget_usage", "recurrence", "user_reason"],
};

export const demoPending: PendingQuestion = {
  question_id: "question-cafe",
  transaction_id: "tx-cafe",
  question: "이 지출이 꼭 필요했던 이유가 뭐야?",
  asked_at: "2026-08-03T02:45:00Z",
  answered_at: null,
  attempt_count: 0,
};

function occurrenceText(count: number): string {
  return ({ 1: "첫 번째", 2: "두 번째", 3: "세 번째" } as Record<number, string>)[count] ?? `${count}번째`;
}

export function demoJudgment(roast: boolean): Judgment {
  const recurrence = occurrenceText(demoSignals.recurrence_30d);
  const budgetUsage = Math.round(demoSignals.budget_usage_after * 100);
  return {
    judgment_id: "judgment-cafe",
    transaction_id: "tx-cafe",
    mode: roast ? "roast" : "normal",
    label: "caution",
    confidence: 0.81,
    rationale: `생활비 예산 ${budgetUsage}%를 사용했고, 이번 주 카페 지출이 ${recurrence}예요.`,
    recommended_action: "이번 주 카페는 여기까지. 다음 만남은 산책으로 바꿔요.",
    message: roast
      ? `아이고 이 화상아, 친구 만난 건 좋다만 이번 주 카페가 벌써 ${recurrence}다. 이번 주 카페는 여기까지 하고, 다음 약속은 산책으로 돌려서 지갑도 숨 좀 쉬자.`
      : `필요한 만남이었지만, 이번 주 카페는 ${recurrence}라 여기까지가 좋아요.`,
    fallback_used: false,
    model: "demo-artifact",
    policy_version: "overspending-v1",
    original_label: "caution",
    effective_label: "caution",
    correction: null,
  };
}
